name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Build and push versioned tags (e.g., v1.0.0)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Step 3: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          variable29/desktop-ml:latest
          variable29/desktop-ml:${{ github.ref_name }}
        # Remove cache-from and cache-to to disable caching

    # Step 5: Verify the image (optional)
    - name: Verify Docker image
      run: |
        docker pull variable29/desktop-ml:latest
        docker run --rm variable29/desktop-ml:latest nvcc --version || echo "CUDA not installed properly"
